/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-06 15:48:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_005fproducts_005fadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add New Products</title>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function validate()\r\n");
      out.write("{\r\n");
      out.write("mess=\"<div class='alert alert-success'><strong>Please Check!</strong> You should enter corret details to enter in the page.</div>\";\r\n");
      out.write("\r\n");
      out.write("  if(!bk_name() || !bk_auther() || !bk_comm() || !bk_price() || !bk_price_dis())\r\n");
      out.write("  {\r\n");
      out.write("    document.getElementById(\"sub\").innerHTML=mess;\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    return true;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("function bk_name(){\r\n");
      out.write("\r\n");
      out.write("  errmsg=\"\";\r\n");
      out.write("  var bname = document.getElementById(\"bname\").value;\r\n");
      out.write("  \r\n");
      out.write("  if(bname == \"\" || bname.length<5)\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"Book Name should be more than 5 letters\";\r\n");
      out.write("    document.getElementById(\"bnamemsg\").innerHTML = errmsg;\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"\";\r\n");
      out.write("    document.getElementById(\"bnamemsg\").innerHTML = errmsg;\r\n");
      out.write("  return true;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function bk_auther()\r\n");
      out.write("{ \r\n");
      out.write("  errmsg=\"\";\r\n");
      out.write("  var bauther = document.getElementById(\"author\").value;\r\n");
      out.write("  \r\n");
      out.write("  if(bauther == \"\" || bauther.length<5)\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"Author Name should be more than 5 letters\";\r\n");
      out.write("    document.getElementById(\"bauthmsg\").innerHTML = errmsg;\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"\";\r\n");
      out.write("    document.getElementById(\"bauthmsg\").innerHTML = errmsg;\r\n");
      out.write("  return true;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function bk_comm(){\r\n");
      out.write("\r\n");
      out.write("errmsg=\"\";\r\n");
      out.write("  var bcomment = document.getElementById(\"description\").value;\r\n");
      out.write("  \r\n");
      out.write("  if(bcomment == \"\" || bcomment.length<100)\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"Pleae enter a detailed description of upto 100 words\";\r\n");
      out.write("    document.getElementById(\"bcomm\").innerHTML = errmsg;\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"\";\r\n");
      out.write("    document.getElementById(\"bcomm\").innerHTML = errmsg;\r\n");
      out.write("  return true;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function bk_price()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("errmsg=\"\";\r\n");
      out.write("  var bpri = document.getElementById(\"price\").value;\r\n");
      out.write("  \r\n");
      out.write("  if(bpri == \"\" || bpri<50)\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"Pleae enter the amount above Rs. 50\";\r\n");
      out.write("    document.getElementById(\"bpr\").innerHTML = errmsg;\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"\";\r\n");
      out.write("    document.getElementById(\"bpr\").innerHTML = errmsg;\r\n");
      out.write("  return true;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function bk_price_dis()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("errmsg=\"\";\r\n");
      out.write("  var bpri = document.getElementById(\"price\").value;\r\n");
      out.write("  var bpri_disc = document.getElementById(\"disprice\").value;\r\n");
      out.write("\r\n");
      out.write("  if(bpri == \"\" || bpri<bpri_disc)\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"You may have not enterd any value in textarea or you've have enterd the Discount amount more than the Orignal price\";\r\n");
      out.write("    document.getElementById(\"bpr_dis\").innerHTML = errmsg;\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    errmsg=\"\";\r\n");
      out.write("    document.getElementById(\"bpr_dis\").innerHTML = errmsg;\r\n");
      out.write("  return true;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"add_new_product.jsp\" onsubmit=\"return validate()\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("             <h2>Book Entry</h2>\r\n");
      out.write("             \r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("               <label for=\"bname\">Book Name</label>\r\n");
      out.write("               <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Enter Book Name\" name=\"name\" onblur=\"bk_name()\">\r\n");
      out.write("               <div id=\"bnamemsg\"></div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"form-group\">\r\n");
      out.write("              <label for=\"author\">Author</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"author\" placeholder=\"Author name\" name=\"author\" onblur=\"bk_auther()\">\r\n");
      out.write("              <div id=\"bauthmsg\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("                <label for=\"description\">\r\n");
      out.write("                    Comments:</label>\r\n");
      out.write("                <textarea class=\"form-control\" name=\"comments\" id=\"comments\" placeholder=\"Description for Book\" maxlength=\"6000\" rows=\"7\" onblur=\"bk_comm()\"></textarea>\r\n");
      out.write("              \r\n");
      out.write("                <div id=\"bcomm\"></div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"price\">Price</label>\r\n");
      out.write("                    <input type=\"number\" class=\"form-control\" id=\"oprice\" placeholder=\"Book price\" name=\"oprice\" onblur=\"bk_price()\">\r\n");
      out.write("                    <div id=\"bpr\"></div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"Discount price\">Price</label>\r\n");
      out.write("                    <input type=\"number\" class=\"form-control\" id=\"dprice\" placeholder=\"Discount Price\" name=\"dprice\" onblur=\"bk_price_dis()\">\r\n");
      out.write("                    <div id=\"bpr_dis\"></div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"frontcover\">Front Cover of Book</label><br>\r\n");
      out.write("              <input type=\"file\" name=\"fcover\" id=\"fcover\" accept=\"image/*\" required=\"required\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"backcover\">Back Cover of Book</label><br>\r\n");
      out.write("                <input type=\"file\" name=\"bcover\" id=\"bcover\" accept=\"image/*\" required=\"required\">\r\n");
      out.write("              </div>\r\n");
      out.write("            \r\n");
      out.write("        <input type=\"submit\" value=\"Register\" class=\"btn btn-dark form-control\" onclick=\"validate()\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <div id=\"sub\"></div>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        \r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
