/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-06 16:18:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.BookStore.Dao.UserDao;
import com.BookStore.User.*;
import java.util.*;

public final class editform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.BookStore.User");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.BookStore.Dao.UserDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #B7CEEC;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


String mob=request.getParameter("mobile");
User u=UserDao.getRecordById(Long.parseLong(mob));


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color: #B7CEEC; height: 100px; width: 100%;\" class=\"d-flex justify-content-center  align-items-center\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"add_product.jsp\" class=\"btn btn-dark\" style=\"height: 80px; width: 250px;\">Add Products</a><br>\r\n");
      out.write("\r\n");
      out.write("<a href=\"admin_view_product.jsp\" class=\"btn btn-dark\" style=\"height: 80px; width: 250px;\">View Products</a>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<a href=\"vieworderadmin.jsp\" class=\"btn btn-dark\" style=\"height: 80px; width: 250px;\">View Order</a>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<a href=\"admin_view_users.jsp\" class=\"btn btn-dark\" style=\"height: 80px; width: 250px;\">View Users</a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"edituser.jsp\" onsubmit=\"return validate()\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("             <h2>Registration</h2>\r\n");
      out.write("       <div class=\"form-group\" >\r\n");
      out.write("             <label for=\"mobile\">Mobile-Number *</label>\r\n");
      out.write("             <input type=\"hidden\" class=\"form-control\" id=\"mobile\" placeholder=\"Number\" onblur=\"ch_number()\"name=\"mobile\" value=\"");
      out.print(u.getMobile());
      out.write("\">\r\n");
      out.write("        <div id=\"pnumber\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("       <div class=\"form-group\" >\r\n");
      out.write("             <label for=\"mobile\">Name *</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Number\" onblur=\"ch_number()\" name=\"name\">\r\n");
      out.write("        <div id=\"pnumber\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\" >\r\n");
      out.write("               <label for=\"Pwd\">Password *</label>\r\n");
      out.write("               <input type=\"text\" class=\"form-control\" id=\"password\" placeholder=\"Enter password\"  onblur=\"ch_pass()\" name=\"password\" value=\"");
      out.print(u.getPassword());
      out.write("\">\r\n");
      out.write("       <div id=\"passerr\"></div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"form-group\">\r\n");
      out.write("               <label for=\"email\">Email *</label>\r\n");
      out.write("               <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Enter email\" onblur=\"ch_email()\" name=\"email\" value=\"");
      out.print(u.getEmail());
      out.write("\">\r\n");
      out.write("         <div id=\"ch_email\"></div>\r\n");
      out.write("         </div>      \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"address\">Address Line 1 *</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"address\" placeholder=\"Enter the full address\" name=\"address\" onblur=\"ch_address()\" value=\"");
      out.print(u.getAddress());
      out.write("\">\r\n");
      out.write("             <div id=\"errp\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"address\">Address Line 2(optional)</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"address1\" placeholder=\"Enter the full address\" name=\"address1\" onblur=\"ch_address()\" value=\"");
      out.print(u.getAddress1());
      out.write("\">\r\n");
      out.write("             <div id=\"errp\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"city\">City *</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"city\" placeholder=\"Enter city\" name=\"city\" required value=\"");
      out.print(u.getCity());
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"pincode\">Pincode *</label>\r\n");
      out.write("             <input type=\"number\" class=\"form-control\" id=\"pincode\" placeholder=\"Enter pincode\" name=\"pincode\" onblur=\"ch_pincode()\" value=\"");
      out.print(u.getPincode());
      out.write("\">\r\n");
      out.write("             <div id=\"pinmess\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <input type=\"submit\" value=\"submit\" class=\"btn btn-dark form-control\" onclick=\"validate()\">\r\n");
      out.write("       <br>\r\n");
      out.write("        <div id=\"sub\"></div>\r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       <br><br><br><br><br>\r\n");
      out.write("       \r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
