/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-06 15:41:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class new_005fuser_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Bootstrap Example</title>\r\n");
      out.write("\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write(" <script>\r\n");
      out.write(" /* \r\n");
      out.write("  function validate()\r\n");
      out.write("  {\r\n");
      out.write("\t  \r\n");
      out.write("\t  mess=\"<br><div class='alert alert-success'><strong>Please Check!</strong> You should enter corret details to enter in the page.</div>\";\r\n");
      out.write("\t  \r\n");
      out.write("\t  if(!ch_number()|| !ch_address() || !ch_pincode() || !ch_pass() || !check_pass()|| !ch_email())\r\n");
      out.write("\t {\r\n");
      out.write("\t\t  document.getElementById(\"sub\").innerHTML=mess;\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t\t  \r\n");
      out.write("\t }\r\n");
      out.write("\t  else\r\n");
      out.write("\t\t  {\r\n");
      out.write("\t\t       return true;\r\n");
      out.write("\t\t  }\r\n");
      out.write("  }\r\n");
      out.write(" */\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  function ch_number()\r\n");
      out.write("  {\r\n");
      out.write("\t  errnumber=\"\";\r\n");
      out.write("\t  var x=document.getElementById(\"mobile\").value;\r\n");
      out.write("\t  var pat=/^[7-9][0-9]{9}$/\r\n");
      out.write("\t  if(pat.test(x))\r\n");
      out.write("\t  {\r\n");
      out.write("\t\t  errnumber=\"Entered Number is valid\";\r\n");
      out.write("\t\t  document.getElementById(\"pnumber\").innerHTML=errnumber;\r\n");
      out.write("\t\t  return true;\r\n");
      out.write("      }\r\n");
      out.write("\t  else\r\n");
      out.write("\t  {\r\n");
      out.write("\t\t  errnumber=\"Entered Number is invalid\";\r\n");
      out.write("\t\t  document.getElementById(\"pnumber\").innerHTML=errnumber;\r\n");
      out.write("\t\t  return false;\t  \r\n");
      out.write("\t  }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function ch_address()\r\n");
      out.write("  {\r\n");
      out.write("\t  errmsg=\"\";\r\n");
      out.write("\t\tvar addr = document.getElementById(\"addressl\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(addr == \"\" || addr.length<6)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//errmsg=\" \";\r\n");
      out.write("\t\t\tdocument.getElementById(\"errp\").innerHTML = 'Address should be maximum 6 characters';\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//errmsg=\"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"errp\").innerHTML = 'Entered value is correct.';\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function ch_pincode()\r\n");
      out.write("  {\r\n");
      out.write("\t  errnumber=\"\";\r\n");
      out.write("\t  var x=document.getElementById(\"pincode\").value;\r\n");
      out.write("\t  var pat=/^[0-9]{6}$/\r\n");
      out.write("\t  if(pat.test(x))\r\n");
      out.write("\t  {\r\n");
      out.write("\t\t  errnumber=\"Entered Pincode is correct\";\r\n");
      out.write("\t\t  document.getElementById(\"pinmess\").innerHTML=errnumber;\r\n");
      out.write("\t\t  return true;\r\n");
      out.write("      }\r\n");
      out.write("\t  else\r\n");
      out.write("\t  {\r\n");
      out.write("\t\t  errnumber=\"The entered pincode is less than 6 digit number, please check\";\r\n");
      out.write("\t\t  document.getElementById(\"pinmess\").innerHTML=errnumber;\r\n");
      out.write("\t\t  return false;\t  \r\n");
      out.write("\t  }\r\n");
      out.write("  } \r\n");
      out.write("  function ch_pass()\r\n");
      out.write("  {\r\n");
      out.write("\r\n");
      out.write("  \terrpss=\"\";\r\n");
      out.write("  \tvar pp=document.getElementById(\"password\").value;\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t//var regexp = new RegExp(var);\r\n");
      out.write("\r\n");
      out.write("  \tif((pp.match(/[a-z]/g) && pp.match(/[A-Z]/g)&& pp.match(/[0-9]/g) && pp.length>=8))\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\t\terrpss=\"Correct Message\";\r\n");
      out.write("  \t\t\tdocument.getElementById(\"passerr\").innerHTML=errpss;\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\treturn true;\r\n");
      out.write("  \t}\r\n");
      out.write("  \telse{\r\n");
      out.write("  \t\t\terrpss=\"Password length should be more than 8 charaters should also contain one Special charater,number and uppercase letter\";\r\n");
      out.write("  \t\tdocument.getElementById(\"passerr\").innerHTML=errpss;\r\n");
      out.write("  \t  \treturn false;\r\n");
      out.write("  \t\r\n");
      out.write("  \t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function check_pass()\r\n");
      out.write("  {\r\n");
      out.write("    errormessagge=\"\";\r\n");
      out.write("  \tvar tp=document.getElementById(\"password\").value;\r\n");
      out.write("  \tvar rp=document.getElementById(\"passwordr\").value;\r\n");
      out.write("  \t\r\n");
      out.write("  \tif(tp!=rp)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\terrormessagge=\"Password Mismatch\";\r\n");
      out.write("  \t\tdocument.getElementById(\"errorp\").innerHTML=errormessagge;\r\n");
      out.write("  \t\r\n");
      out.write("  \t\treturn false;\r\n");
      out.write("  \t}\r\n");
      out.write("  \telse\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\terrormessagge=\"Correct Password\";\r\n");
      out.write("  \t\tdocument.getElementById(\"errorp\").innerHTML=errormessagge;\r\n");
      out.write("  \t\treturn true;\r\n");
      out.write("  \t}\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  function ch_email()\r\n");
      out.write("  {\r\n");
      out.write("  var mail=document.getElementById('email').value;\r\n");
      out.write("  var mail_pattern=/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/;\r\n");
      out.write("\r\n");
      out.write("  if(mail=='')\r\n");
      out.write("  {\r\n");
      out.write("  document.getElementById('ch_email').innerHTML='Enter Your E-MailID';\r\n");
      out.write("  return false;\r\n");
      out.write("  }\r\n");
      out.write("  else if(mail_pattern.test(mail)==false)\r\n");
      out.write("  {\r\n");
      out.write("  document.getElementById('ch_email').innerHTML='Entered Email Id is Invalid';\r\n");
      out.write("  return false;\r\n");
      out.write("  }\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("  document.getElementById('ch_email').innerHTML='Entered Email Id is Valid';\r\n");
      out.write("  }\r\n");
      out.write("  }  \r\n");
      out.write(" \r\n");
      out.write(" </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");



      out.write("\r\n");
      out.write("<form action=\"add_new_user.jsp\" onsubmit=\"return validate()\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("             <h2>Registration</h2>\r\n");
      out.write("       <div class=\"form-group\" >\r\n");
      out.write("             <label for=\"mobile\">Mobile-Number *</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"mobile\" placeholder=\"Number\" onblur=\"ch_number()\"name=\"mobile\">\r\n");
      out.write("        <div id=\"pnumber\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("       <div class=\"form-group\" >\r\n");
      out.write("             <label for=\"mobile\">Name *</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Number\" onblur=\"ch_number()\" name=\"name\">\r\n");
      out.write("        <div id=\"pnumber\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"form-group\" >\r\n");
      out.write("               <label for=\"Pwd\">Password *</label>\r\n");
      out.write("               <input type=\"password\" class=\"form-control\" id=\"password\" placeholder=\"Enter password\"  onblur=\"ch_pass()\" name=\"password\">\r\n");
      out.write("       <div id=\"passerr\"></div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class=\"form-group\" >\r\n");
      out.write("              <label for=\"Pwd\">confirm-Password *</label>\r\n");
      out.write("              <input type=\"password\" class=\"form-control\" id=\"passwordr\" placeholder=\"Re-Enter password\" onblur=\"check_pass()\" name=\"cnfpassword\" >\r\n");
      out.write("        <div id=\"errorp\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("       <div class=\"form-group\">\r\n");
      out.write("               <label for=\"email\">Email *</label>\r\n");
      out.write("               <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Enter email\" onblur=\"ch_email()\" name=\"email\" >\r\n");
      out.write("         <div id=\"ch_email\"></div>\r\n");
      out.write("         </div>      \r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"address\">Address Line 1 *</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"address\" placeholder=\"Enter the full address\" name=\"address\" onblur=\"ch_address()\" >\r\n");
      out.write("             <div id=\"errp\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"address\">Address Line 2(optional)</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"address1\" placeholder=\"Enter the full address\" name=\"address1\" onblur=\"ch_address()\">\r\n");
      out.write("             <div id=\"errp\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"city\">City *</label>\r\n");
      out.write("             <input type=\"text\" class=\"form-control\" id=\"city\" placeholder=\"Enter city\" name=\"city\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("             <label for=\"pincode\">Pincode *</label>\r\n");
      out.write("             <input type=\"number\" class=\"form-control\" id=\"pincode\" placeholder=\"Enter pincode\" name=\"pincode\" onblur=\"ch_pincode()\">\r\n");
      out.write("             <div id=\"pinmess\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("        <p><input type=\"checkbox\" required> Please accept our term and conditions !!!</p>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"submit\" value=\"submit\" class=\"btn btn-dark form-control\" onclick=\"validate()\">\r\n");
      out.write("       <br>\r\n");
      out.write("        <div id=\"sub\"></div>\r\n");
      out.write("       \r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       <br><br><br><br><br>\r\n");
      out.write("       \r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
